### ISSUE TITLE
the Ore generation of lanthanum isn't working

### ISSUE THREAD

**Issue by lingyunmo** [lingyunmo/Lanthanum#16]
the Ore generation of lanthanum isn't working,but the generation of the Gemstone are very well.That's pretty weird.If you know what's going on,plz see the 'newOre' branch.

**Comment by lingyunmo** [comment]
#17 here.

**Comment by Stablaze** [comment]
middle,small,upper's name wasn' t change properly. #18

**Comment by lingyunmo** [comment]
that's nice of you!
